export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'

export const FETCH_HEROES_INIT = 'FETCH_HEROES_INIT'
export const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS'
export const FETCH_HEROES_FAIL = 'FETCH_HEROES_FAIL'

export const SET_NB_RESULTS = 'SET_NB_RESULTS'
export const UPDATE_PARAMS = 'UPDATE_PARAMS'